image: nixos/unstable
environment:
  REPO_NAME: standupbot
triggers:
  - action: email
    condition: failure
    to: alerts@sumnerevans.com
artifacts:
  - standupbot/standupbot
tasks:
  - setup: |
      cd $REPO_NAME
      echo "cd $REPO_NAME" >> ~/.buildenv
      nix-shell \
        --arg forCI true \
        --run "echo SHELL BUILD COMPLETE"

  - build: |
      nix-shell \
        --arg forCI true \
        --run "go build -v"

  - test: |
      nix-shell \
        --arg forCI true \
        --run "go test -v"
